# Generated by Django 5.2.4 on 2025-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_room_lookup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='lookup_id',
        ),
        migrations.AddField(
            model_name='room',
            name='username',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
