# Generated by Django 5.2.4 on 2025-08-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_room_lookup_id_room_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
    ]
