# Generated by Django 5.2.5 on 2025-08-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_room_id_alter_todoitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='room',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.room')),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todolist.category'),
        ),
    ]
