# Generated by Django 5.2.5 on 2025-08-21 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_remove_todoitem_room_category_todoitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='todolist.room'),
        ),
    ]
