# Generated by Django 5.2.5 on 2025-08-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_category_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
    ]
