# Generated by Django 5.2.5 on 2025-08-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_remove_todoitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='is_done',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
