# Generated by Django 5.2.5 on 2025-08-23 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_remove_todoitem_is_done_todoitem_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['position']},
        ),
    ]
